env: standard
instance_class: F2
runtime: nodejs14
service: default
entrypoint: node --es-module-specifier-resolution=node ./build/index.js

handlers:
- url: /pckoubou/names
  script: auto

- url: /pckoubou/prices
  script: auto

- url: /pckoubou/id
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 0
