env: standard
instance_class: F2
runtime: nodejs14
service: default
main: ./src/server
entrypoint: yarn workspace server bck

handlers:
- url: /pckoubou/names
  script: auto

- url: /pckoubou/prices
  script: auto

- url: /pckoubou/id
  script: auto

automatic_scaling:
  min_instances: 0
  max_instances: 0
