env: standard
instance_class: F2
runtime: nodejs14
service: default
entrypoint: node --es-module-specifier-resolution=node ./src/server/build/index.js

handlers:
- url: /pckoubou/names
  script: auto
  http_headers:
    Access-Control-Allow-Origin: https://gpuscraping.azurewebsites.net

- url: /pckoubou/prices
  script: auto
  http_headers:
    Access-Control-Allow-Origin: https://gpuscraping.azurewebsites.net

- url: /pckoubou/id
  script: auto
  http_headers:
    Access-Control-Allow-Origin: https://gpuscraping.azurewebsites.net

automatic_scaling:
  min_instances: 0
  max_instances: 0
