
steps:
  - name: 'gcr.io/cloud-builders/yarn'
    args: ['install']
    dir: ./src/server

  - name: 'gcr.io/cloud-builders/yarn'
    args: ['build']
    dir: ./src/server

  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', './src/server/app.yaml']
